### ISSUE TITLE
Doesn't work with ggplot

### ISSUE THREAD

**Issue by royfrancis** [johnbaums/hues#2]
Works fine with `barplot()`

```r
barplot(rep(1,5),col=iwanthue(5))
```
![1](https://user-images.githubusercontent.com/5083500/35238278-4d83750a-ffad-11e7-934f-86eb46a3a1a5.png)

but, doesn't work with `ggplot()`

```r
library(ggplot2)
ggplot(data.frame(x=1:5,y=1:5),aes(x,y,fill=cut(x,breaks=5)))+
 geom_bar(stat="identity")+
 scale_fill_manual(values=iwanthue(5))
```

![2](https://user-images.githubusercontent.com/5083500/35238304-5bcfd20c-ffad-11e7-8b29-c7df386adaad.png)

**Comment by royfrancis** [comment]
Weird enough, it works when inside `as.character()`.

```r
ggplot(data.frame(x=1:5,y=1:5),aes(x,y,fill=cut(x,breaks=5)))+
 geom_bar(stat="identity")+
 scale_fill_manual(values=as.character(iwanthue(5)))
```

![2](https://user-images.githubusercontent.com/5083500/35238619-4b24d654-ffae-11e7-98a0-5a90841cd77b.png)

**Comment by rdinnager** [comment]
This behaviour is because `iwanthue` produces a named vector (where the names are `as.character(1:n)`). `ggplot2`'s `scale_fill_manual` will match variables levels to the provided palette by matching to the vector's names, if the vector has names. `as.character` removes the names of the vector produced by `iwanthue`, and when a vector has no names `ggplot2` will just match based on order, which is the behaviour @royfrancis was expecting. `unname(iwanthue(5))` also works. I'd actually recommend removing the vector names from the output of `iwanthue` as they don't seem to serve a purpose.

**Comment by johnbaums** [comment]
@royfrancis v0.2.0 is now on CRAN, and provides better ggplot support thanks to @rdinnager. The following will work now.

```
ggplot(data.frame(x=1:5,y=1:5),aes(x,y,fill=cut(x,breaks=5)))+
  geom_bar(stat="identity")+
  hues::scale_fill_iwanthue()
```
